window.PORTFOLIO_I18N = {
  "en": {
    "copper-observatory.title": "Chile’s copper: volume versus value",
    "copper-observatory.domain": "Mining · Official public data",
    "copper-observatory.question": "What should management monitor when export value grows faster than production?",
    "copper-observatory.method": "Reconcile 49 annual observations from three Cochilco workbooks. Normalize years, verify one-to-one joins, compare growth rates and index each series to 1976. SQL window functions reproduce the annual changes.",
    "copper-observatory.result": "In 2024 production rose 4.9%, nominal export value 16.7% and nominal LME price 7.9%. Export growth is not a production-growth metric.",
    "copper-observatory.decision": "Maintain separate physical-volume, price and export-value indicators. Investigate their divergence before revising operating capacity assumptions.",
    "copper-observatory.limits": "Aggregate annual history through 2024; no mine-level costs, sale contracts or export tonnage. Prices and export values are nominal. Correlation between changes (0.923) is descriptive, not causal. A source typo in 1951 lies outside the 1976–2024 scope; it was not silently corrected.",
    "copper-observatory.metricLabel": "years reconciled",
    "feria-demand.title": "A forecast a small business can operate",
    "feria-demand.domain": "Demand planning · Synthetic simulation",
    "feria-demand.question": "With only date, product and demand, can a transparent forecast improve on repeating last week?",
    "feria-demand.method": "Generate 140,288 daily records for 128 products with a fixed seed. Compare seasonal naive with an eight-week weekday mean over four validation origins; reserve December for one final 28-day hold-out. Forecasts remain fixed at each origin.",
    "feria-demand.result": "The weekday mean reduces held-out WMAPE from 44.6% to 35.9%: a 19.4% relative reduction. 69 products enter volume class A, including the item crossing the 80% threshold.",
    "feria-demand.decision": "Start with the weekday mean as a planning input. Collect stock availability, lead times and actual transactions before recommending reorder quantities or monetizing savings.",
    "feria-demand.limits": "All records are synthetic, not reconstructed client evidence. No prices, lost-sales observations, stock, shelf life or lead times. Volume classes are not revenue ABC. Results describe this generator, not a real business or service-level improvement.",
    "feria-demand.metricLabel": "less forecast error · simulated hold-out",
    "bank-campaign.title": "When a banking model should not ship",
    "bank-campaign.domain": "Banking · Historical academic dataset",
    "bank-campaign.question": "Can contact capacity be prioritized using information available before a call—and does that ranking survive a later cohort?",
    "bank-campaign.method": "Use UCI’s 41,188 chronologically ordered records. Split 60/20/20 without shuffling, fit preprocessing on training only and exclude call duration, current campaign count and demographic fields. Audit ranking and calibration on reserved data.",
    "bank-campaign.result": "Held-out AUC is 0.458. At 20% capacity the model captures 26.7% of observed subscribers, but the response rate shifts from 4.8% in training to 30.8% in hold-out. The positive top-capacity lift does not rescue overall ranking or calibration.",
    "bank-campaign.decision": "Do not deploy this model. Investigate cohort construction and macroeconomic drift, obtain recent pre-contact data and validate a new policy before an experiment. No campaign ROI or causal uplift is claimed.",
    "bank-campaign.limits": "Portuguese campaigns from 2008–2010, not current Chilean banking. UCI supplies row order but no exact dates or customer IDs; repeat-client leakage cannot be ruled out. Outcome is term-deposit subscription, not default risk. Reported capture is observational. Validation AP was already below cohort prevalence; hold-out is a diagnostic audit, not evidence supporting deployment.",
    "bank-campaign.metricLabel": "held-out AUC · model rejected",
    "hero.tagline": "SQL, Python and BI for better operational decisions.",
    "hero.summary": "Data Analyst with a background in B2B SaaS and compliance reporting. I build reliable datasets, evaluate forecasts and translate findings into practical recommendations. Explore six documented projects in retail, logistics, mining and banking.",
    "proj.title": "The evidence behind the decision",
    "proj.lead": "Six cases, from business question to evidence. Open the analysis, explore a dashboard or download the complete files.",
    "evidence.read": "Read case study",
    "about.p2": "My professional background is in compliance reporting, SQL automation and BI. The public studies above are separate analytical demonstrations; they do not recreate confidential employment records.",
    "exp.job2.role": "Independent project — Market demand analytics",
    "exp.job2.period": "Sep 2026",
    "exp.job2.company": "Market demand simulation · Independent project",
    "exp.job2.b1": "Developed a reproducible simulation inspired by a small market business.",
    "exp.job2.b2": "Structured product demand and compared transparent forecast baselines.",
    "exp.job2.b3": "Separated observed data, assumptions and simulated outcomes in project documentation.",
    "exp.job2.b4": "Prepared SQL analysis and downloadable workbooks for review.",
    "market-stall-analytics.title": "Waste and replenishment control",
    "market-stall-analytics.decision": "Prioritize an olives waste pilot before approving cold-storage investment or automated orders. The category accounts for CLP 2,984,432 in simulated cohort waste at acquisition cost.",
    "market-stall-analytics.scope": "128 products, 22 suppliers and 3,825 synthetic batches. Purchases span July 2023 to June 2025. Closures extend to 2035; full cohort results are not two-year realized sales.",
    "grocery-replenishment-policy.title": "Forecasting for a replenishment pilot",
    "grocery-replenishment-policy.decision": "Recursive LightGBM was selected through temporal validation. Use it in a shadow pilot: aggregate performance improves, but intermittent demand leaves substantial SKU-store error.",
    "grocery-replenishment-policy.scope": "Synthetic data, seed 42. 110,624 source records, 60 products, six stores and 360 series. The completed calendar contains 213,480 rows from January 2015 to August 2016.",
    "airline-reliability.title": "Air route reliability",
    "airline-reliability.decision": "Review Atlanta-Orlando connections first by disrupted-flight volume in June 2023. Investigate scheduling and contingency handling without attributing causes or recommending capacity reductions from one month.",
    "airline-reliability.scope": "577,262 BTS-reported flights in June 2023 across 5,808 directional routes. Cancellations and diversions are retained. The source is public and official; the period is historical.",
    "proj.more": "Mining, banking and forecast fundamentals",
    "exp.job1.b2": "Developed Power BI and Tableau dashboards for contractor reporting and operational monitoring.",
    "exp.job1.b3": "Automated document-verification workflows using SQL and structured data checks.",
    "exp.job1.b4": "Worked on compliance reporting and anomaly analysis with SQL and Python.",
    "about.p1": "I am a Data Analyst based in Chile with experience in SQL automation, compliance reporting, Python analysis and KPI dashboards in Power BI and Tableau."
  },
  "es": {
    "copper-observatory.title": "Cobre chileno: volumen frente a valor",
    "copper-observatory.domain": "Minería · Datos públicos oficiales",
    "copper-observatory.question": "¿Qué debe vigilar la gerencia cuando el valor exportado crece más que la producción?",
    "copper-observatory.method": "Conciliación de 49 observaciones anuales de tres archivos Cochilco. Normalización de años, uniones uno a uno, variaciones e índices base 1976. Funciones de ventana SQL reproducen las variaciones.",
    "copper-observatory.result": "En 2024 la producción creció 4,9%, el valor nominal exportado 16,7% y el precio nominal LME 7,9%. El crecimiento exportador no mide el crecimiento productivo.",
    "copper-observatory.decision": "Mantener indicadores separados de volumen físico, precio y valor exportado. Investigar sus diferencias antes de revisar supuestos de capacidad operativa.",
    "copper-observatory.limits": "Historia anual agregada hasta 2024; sin costos por faena, contratos ni tonelaje exportado. Precios y exportaciones nominales. Correlación entre variaciones (0,923) descriptiva, no causal. Un error de año en 1951 está fuera del período; no se corrigió silenciosamente.",
    "copper-observatory.metricLabel": "años conciliados",
    "feria-demand.title": "Un pronóstico que una feria puede operar",
    "feria-demand.domain": "Planificación de demanda · Simulación sintética",
    "feria-demand.question": "Con solo fecha, producto y demanda, ¿un pronóstico transparente mejora repetir la última semana?",
    "feria-demand.method": "Generar 140.288 registros diarios de 128 productos con semilla fija. Comparar naive estacional con promedio de ocho semanas por día, en cuatro orígenes de validación; reservar diciembre como prueba final de 28 días. Cada pronóstico queda fijo en su origen.",
    "feria-demand.result": "El promedio por día reduce WMAPE de prueba de 44,6% a 35,9%: una reducción relativa de 19,4%. 69 productos quedan en clase A por volumen, incluyendo el que cruza el umbral de 80%.",
    "feria-demand.decision": "Usar el promedio por día como insumo de planificación. Recopilar disponibilidad, plazos y transacciones reales antes de recomendar cantidades de reposición o monetizar ahorros.",
    "feria-demand.limits": "Todos los registros son sintéticos, no evidencia reconstruida de un cliente. Sin precios, ventas perdidas, stock, vida útil ni plazos. La clasificación por volumen no es ABC de ingresos. Resultados de este generador, no de un negocio real ni de mejora de servicio.",
    "feria-demand.metricLabel": "menos error · prueba simulada",
    "bank-campaign.title": "Cuándo no desplegar un modelo bancario",
    "bank-campaign.domain": "Banca · Dataset académico histórico",
    "bank-campaign.question": "¿Se puede priorizar capacidad de contacto con información previa a la llamada y mantener el desempeño en una cohorte posterior?",
    "bank-campaign.method": "Usar los 41.188 registros cronológicos de UCI. Separar 60/20/20 sin mezclar, ajustar transformaciones solo en entrenamiento y excluir duración, contactos de campaña actual y demografía. Auditar ranking y calibración en datos reservados.",
    "bank-campaign.result": "AUC de prueba de 0,458. Con 20% de capacidad captura 26,7% de suscriptores observados, pero la tasa cambia de 4,8% en entrenamiento a 30,8% en prueba. El lift positivo a capacidad limitada no rescata el ranking global ni la calibración.",
    "bank-campaign.decision": "No desplegar este modelo. Investigar composición de cohortes y cambio macroeconómico, obtener datos recientes previos al contacto y validar otra política antes de experimentar. No se afirma ROI ni uplift causal.",
    "bank-campaign.limits": "Campañas portuguesas de 2008–2010, no banca chilena actual. UCI aporta orden pero no fechas exactas ni IDs; no se descarta repetición de clientes entre particiones. Se predice suscripción de depósitos, no impago. Captura observacional. AP de validación ya inferior a prevalencia; prueba final diagnóstica, no evidencia para desplegar.",
    "bank-campaign.metricLabel": "AUC de prueba · modelo rechazado",
    "hero.tagline": "SQL, Python y BI para mejores decisiones operativas.",
    "hero.summary": "Analista de Datos con experiencia en SaaS B2B y reportes de cumplimiento. Construyo bases confiables, evalúo pronósticos y traduzco hallazgos en recomendaciones prácticas. Explora seis proyectos documentados de retail, logística, minería y banca.",
    "proj.title": "La evidencia detrás de la decisión",
    "proj.lead": "Seis casos, desde la pregunta de negocio hasta la evidencia. Revisa el análisis, explora un dashboard o descarga los archivos completos.",
    "evidence.read": "Leer caso completo",
    "about.p2": "Mi experiencia profesional se centra en reportes de cumplimiento, automatización SQL y BI. Los casos públicos son demostraciones analíticas independientes; no recrean registros laborales confidenciales.",
    "exp.job2.role": "Proyecto independiente — Analítica de demanda de feria",
    "exp.job2.period": "Sep 2026",
    "exp.job2.company": "Simulación de demanda de feria · Proyecto independiente",
    "exp.job2.b1": "Desarrollé una simulación reproducible inspirada en un negocio de feria.",
    "exp.job2.b2": "Estructuré demanda por producto y comparé pronósticos transparentes.",
    "exp.job2.b3": "Separé datos observados, supuestos y resultados simulados en la documentación.",
    "exp.job2.b4": "Preparé análisis SQL y archivos descargables para revisión.",
    "market-stall-analytics.title": "Control de merma y reposición",
    "market-stall-analytics.decision": "Priorizar un piloto de merma en aceitunas antes de aprobar inversión en frío o emitir órdenes automáticas. La categoría concentra CLP 2.984.432 de merma valorada al costo en las cohortes simuladas.",
    "market-stall-analytics.scope": "128 productos, 22 proveedores y 3.825 lotes simulados. Compras de julio de 2023 a junio de 2025. Los cierres llegan hasta 2035; los resultados completos no son ventas realizadas en dos años.",
    "grocery-replenishment-policy.title": "Pronóstico para un piloto de reposición",
    "grocery-replenishment-policy.decision": "LightGBM recursivo fue seleccionado mediante validación temporal. Usarlo en un piloto en sombra: el desempeño agregado mejora, pero la demanda intermitente mantiene un error alto por SKU y tienda.",
    "grocery-replenishment-policy.scope": "Datos sintéticos con semilla 42. 110.624 registros originales, 60 productos, seis tiendas y 360 series. El calendario completo contiene 213.480 filas entre enero de 2015 y agosto de 2016.",
    "airline-reliability.title": "Confiabilidad de rutas aéreas",
    "airline-reliability.decision": "Revisar primero las conexiones Atlanta y Orlando por volumen de vuelos afectados en junio de 2023. La recomendación es investigar programación y contingencias, sin atribuir causas ni proponer reducciones de capacidad con un solo mes.",
    "airline-reliability.scope": "577.262 vuelos reportados por BTS en junio de 2023, en 5.808 rutas direccionales. Se conservan cancelaciones y desvíos. La fuente es pública y oficial; el período es histórico.",
    "proj.more": "Minería, banca y fundamentos de pronóstico",
    "exp.job1.b2": "Desarrollé dashboards en Power BI y Tableau para reportes de contratistas y seguimiento operacional.",
    "exp.job1.b3": "Automaticé flujos de verificación documental con SQL y controles de datos estructurados.",
    "exp.job1.b4": "Trabajé en reportes de cumplimiento y análisis de anomalías con SQL y Python.",
    "about.p1": "Soy Analista de Datos en Chile con experiencia en automatización SQL, reportes de cumplimiento, análisis Python y dashboards de KPIs en Power BI y Tableau."
  }
};
