window.PORTFOLIO_I18N = {
  "en": {
    "copper-observatory.title": "Chile’s copper: volume versus value",
    "copper-observatory.domain": "Mining · Official public data",
    "copper-observatory.question": "What should management monitor when export value grows faster than production?",
    "copper-observatory.method": "Reconcile 49 annual observations from three Cochilco workbooks. Normalize years, verify one-to-one joins, compare growth rates and index each series to 1976. SQL window functions reproduce the annual changes.",
    "copper-observatory.result": "In 2024 production rose 4.9%, nominal export value 16.7% and nominal LME price 7.9%. Export growth is not a production-growth metric.",
    "copper-observatory.decision": "Maintain separate physical-volume, price and export-value indicators. Investigate their divergence before revising operating capacity assumptions.",
    "copper-observatory.limits": "Aggregate annual history through 2024; no mine-level costs, sale contracts or export tonnage. Prices and export values are nominal. Correlation between changes (0.923) is descriptive, not causal. A source typo in 1951 lies outside the 1976–2024 scope; it was not silently corrected.",
    "copper-observatory.metricLabel": "years reconciled",
    "feria-demand.title": "A forecast a small business can operate",
    "feria-demand.domain": "Demand planning · Synthetic simulation",
    "feria-demand.question": "With only date, product and demand, can a transparent forecast improve on repeating last week?",
    "feria-demand.method": "Generate 140,288 daily records for 128 products with a fixed seed. Compare seasonal naive with an eight-week weekday mean over four validation origins; reserve December for one final 28-day hold-out. Forecasts remain fixed at each origin.",
    "feria-demand.result": "The weekday mean reduces held-out WMAPE from 44.6% to 35.9%: a 19.4% relative reduction. 69 products enter volume class A, including the item crossing the 80% threshold.",
    "feria-demand.decision": "Start with the weekday mean as a planning input. Collect stock availability, lead times and actual transactions before recommending reorder quantities or monetizing savings.",
    "feria-demand.limits": "All records are synthetic, not reconstructed client evidence. No prices, lost-sales observations, stock, shelf life or lead times. Volume classes are not revenue ABC. Results describe this generator, not a real business or service-level improvement.",
    "feria-demand.metricLabel": "less forecast error · simulated hold-out",
    "bank-campaign.title": "When a banking model should not ship",
    "bank-campaign.domain": "Banking · Historical academic dataset",
    "bank-campaign.question": "Can contact capacity be prioritized using information available before a call—and does that ranking survive a later cohort?",
    "bank-campaign.method": "Use UCI’s 41,188 chronologically ordered records. Split 60/20/20 without shuffling, fit preprocessing on training only and exclude call duration, current campaign count and demographic fields. Audit ranking and calibration on reserved data.",
    "bank-campaign.result": "Held-out AUC is 0.458. At 20% capacity the model captures 26.7% of observed subscribers, but the response rate shifts from 4.8% in training to 30.8% in hold-out. The positive top-capacity lift does not rescue overall ranking or calibration.",
    "bank-campaign.decision": "Do not deploy this model. Investigate cohort construction and macroeconomic drift, obtain recent pre-contact data and validate a new policy before an experiment. No campaign ROI or causal uplift is claimed.",
    "bank-campaign.limits": "Portuguese campaigns from 2008–2010, not current Chilean banking. UCI supplies row order but no exact dates or customer IDs; repeat-client leakage cannot be ruled out. Outcome is term-deposit subscription, not default risk. Reported capture is observational. Validation AP was already below cohort prevalence; hold-out is a diagnostic audit, not evidence supporting deployment.",
    "bank-campaign.metricLabel": "held-out AUC · model rejected",
    "hero.tagline": "From business questions to decisions you can audit.",
    "hero.summary": "Data Analyst focused on SQL, Python, Excel and business intelligence. Explore public-data studies and clearly identified simulations: the method, the result and the limits behind each recommendation.",
    "proj.title": "The evidence behind the decision",
    "proj.lead": "Three business questions. Reproducible data, transparent validation and downloadable workbooks.",
    "evidence.read": "Read case study",
    "about.p2": "My professional background is in compliance reporting, SQL automation and BI. The public studies above are separate analytical demonstrations; they do not recreate confidential employment records.",
    "exp.job2.role": "Independent project — Market demand analytics",
    "exp.job2.period": "Sep 2026",
    "exp.job2.company": "Market demand simulation · Independent project",
    "exp.job2.b1": "Developed a reproducible simulation inspired by a small market business.",
    "exp.job2.b2": "Structured product demand and compared transparent forecast baselines.",
    "exp.job2.b3": "Separated observed data, assumptions and simulated outcomes in project documentation.",
    "exp.job2.b4": "Prepared SQL analysis and downloadable workbooks for review."
  },
  "es": {
    "copper-observatory.title": "Cobre chileno: volumen frente a valor",
    "copper-observatory.domain": "Minería · Datos públicos oficiales",
    "copper-observatory.question": "¿Qué debe vigilar la gerencia cuando el valor exportado crece más que la producción?",
    "copper-observatory.method": "Conciliación de 49 observaciones anuales de tres archivos Cochilco. Normalización de años, uniones uno a uno, variaciones e índices base 1976. Funciones de ventana SQL reproducen las variaciones.",
    "copper-observatory.result": "En 2024 la producción creció 4,9%, el valor nominal exportado 16,7% y el precio nominal LME 7,9%. El crecimiento exportador no mide el crecimiento productivo.",
    "copper-observatory.decision": "Mantener indicadores separados de volumen físico, precio y valor exportado. Investigar sus diferencias antes de revisar supuestos de capacidad operativa.",
    "copper-observatory.limits": "Historia anual agregada hasta 2024; sin costos por faena, contratos ni tonelaje exportado. Precios y exportaciones nominales. Correlación entre variaciones (0,923) descriptiva, no causal. Un error de año en 1951 está fuera del período; no se corrigió silenciosamente.",
    "copper-observatory.metricLabel": "años conciliados",
    "feria-demand.title": "Un pronóstico que una feria puede operar",
    "feria-demand.domain": "Planificación de demanda · Simulación sintética",
    "feria-demand.question": "Con solo fecha, producto y demanda, ¿un pronóstico transparente mejora repetir la última semana?",
    "feria-demand.method": "Generar 140.288 registros diarios de 128 productos con semilla fija. Comparar naive estacional con promedio de ocho semanas por día, en cuatro orígenes de validación; reservar diciembre como prueba final de 28 días. Cada pronóstico queda fijo en su origen.",
    "feria-demand.result": "El promedio por día reduce WMAPE de prueba de 44,6% a 35,9%: una reducción relativa de 19,4%. 69 productos quedan en clase A por volumen, incluyendo el que cruza el umbral de 80%.",
    "feria-demand.decision": "Usar el promedio por día como insumo de planificación. Recopilar disponibilidad, plazos y transacciones reales antes de recomendar cantidades de reposición o monetizar ahorros.",
    "feria-demand.limits": "Todos los registros son sintéticos, no evidencia reconstruida de un cliente. Sin precios, ventas perdidas, stock, vida útil ni plazos. La clasificación por volumen no es ABC de ingresos. Resultados de este generador, no de un negocio real ni de mejora de servicio.",
    "feria-demand.metricLabel": "menos error · prueba simulada",
    "bank-campaign.title": "Cuándo no desplegar un modelo bancario",
    "bank-campaign.domain": "Banca · Dataset académico histórico",
    "bank-campaign.question": "¿Se puede priorizar capacidad de contacto con información previa a la llamada y mantener el desempeño en una cohorte posterior?",
    "bank-campaign.method": "Usar los 41.188 registros cronológicos de UCI. Separar 60/20/20 sin mezclar, ajustar transformaciones solo en entrenamiento y excluir duración, contactos de campaña actual y demografía. Auditar ranking y calibración en datos reservados.",
    "bank-campaign.result": "AUC de prueba de 0,458. Con 20% de capacidad captura 26,7% de suscriptores observados, pero la tasa cambia de 4,8% en entrenamiento a 30,8% en prueba. El lift positivo a capacidad limitada no rescata el ranking global ni la calibración.",
    "bank-campaign.decision": "No desplegar este modelo. Investigar composición de cohortes y cambio macroeconómico, obtener datos recientes previos al contacto y validar otra política antes de experimentar. No se afirma ROI ni uplift causal.",
    "bank-campaign.limits": "Campañas portuguesas de 2008–2010, no banca chilena actual. UCI aporta orden pero no fechas exactas ni IDs; no se descarta repetición de clientes entre particiones. Se predice suscripción de depósitos, no impago. Captura observacional. AP de validación ya inferior a prevalencia; prueba final diagnóstica, no evidencia para desplegar.",
    "bank-campaign.metricLabel": "AUC de prueba · modelo rechazado",
    "hero.tagline": "De preguntas de negocio a decisiones que puedes revisar.",
    "hero.summary": "Data Analyst enfocado en SQL, Python, Excel e inteligencia de negocios. Explora análisis de datos públicos y simulaciones identificadas: método, resultado y límites detrás de cada recomendación.",
    "proj.title": "La evidencia detrás de la decisión",
    "proj.lead": "Tres preguntas de negocio. Datos reproducibles, validación transparente y archivos descargables.",
    "evidence.read": "Leer caso completo",
    "about.p2": "Mi experiencia profesional se centra en reportes de cumplimiento, automatización SQL y BI. Los casos públicos son demostraciones analíticas independientes; no recrean registros laborales confidenciales.",
    "exp.job2.role": "Proyecto independiente — Analítica de demanda de feria",
    "exp.job2.period": "Sep 2026",
    "exp.job2.company": "Simulación de demanda de feria · Proyecto independiente",
    "exp.job2.b1": "Desarrollé una simulación reproducible inspirada en un negocio de feria.",
    "exp.job2.b2": "Estructuré demanda por producto y comparé pronósticos transparentes.",
    "exp.job2.b3": "Separé datos observados, supuestos y resultados simulados en la documentación.",
    "exp.job2.b4": "Preparé análisis SQL y archivos descargables para revisión."
  }
};
