table Annual
	column year
		dataType: int64
		sourceColumn: year
		summarizeBy: none

	column production_kt
		dataType: double
		sourceColumn: production_kt
		summarizeBy: sum

	column price_us_cent_lb
		dataType: double
		sourceColumn: price_us_cent_lb
		summarizeBy: sum

	column exports_usd_m
		dataType: double
		sourceColumn: exports_usd_m
		summarizeBy: sum

	measure 'Production kt' = SUM(Annual[production_kt])
		formatString: #,0.0

	measure 'Exports USD m' = SUM(Annual[exports_usd_m])
		formatString: #,0.0

	measure 'Price cents lb' = AVERAGE(Annual[price_us_cent_lb])
		formatString: #,0.0

	partition Annual = m
		mode: import
		source =
			let
			 Source = Csv.Document(Binary.FromText("eWVhcixwcm9kdWN0aW9uX2t0LHByaWNlX3VzX2NlbnRfbGIsZXhwb3J0c191c2RfbQ0KMTk3NiwxMDA1LjIsNjMuNjExLDEyMzMuMg0KMTk3NywxMDU2LjIsNTkuMjksMTE2MS40DQoxOTc4LDEwMzUuNSw2MS44ODYsMTIxOC43DQoxOTc5LDEwNjUuMCw4OS44MywxODg3LjkNCjE5ODAsMTA3NC42LDk5LjE3NCwyMTI0LjcNCjE5ODEsMTA4MS4xLDc4Ljk0OSwxNzM3LjgNCjE5ODIsMTI0MC43LDY3LjA1NywxNjg0LjYNCjE5ODMsMTI1Ny4yLDcyLjE3MywxODc0LjkNCjE5ODQsMTI5MC4wLDYyLjQ0OSwxNjAzLjkNCjE5ODUsMTM1Ni4wLDY0LjI4MSwxNzg4LjcNCjE5ODYsMTQwMS4xLDYyLjI4NywxNzU3LjENCjE5ODcsMTQxOC4zLDgxLjA4NiwyMjM0LjcNCjE5ODgsMTQ1MS4wLDExNy45MzcsMzQxNi4yDQoxOTg5LDE2MDkuMywxMjkuMTEzLDQwMjEuNA0KMTk5MCwxNTg4LjQsMTIwLjg3OSwzODEwLjINCjE5OTEsMTgxNC4zLDEwNi4wNjYsMzYxNy4zDQoxOTkyLDE5MzIuNywxMDMuNTczLDM4ODYuMA0KMTk5MywyMDU1LjQsODYuNzEzLDMyNDcuOA0KMTk5NCwyMjE5LjksMTA0LjkwMyw0MjQyLjANCjE5OTUsMjQ4OC42LDEzMy4xOTgsNjQ4Ny4xDQoxOTk2LDMxMTUuOCwxMDMuODk0LDU4MzguNQ0KMTk5NywzMzkyLjAsMTAzLjIyNCw2ODUxLjANCjE5OTgsMzY4Ni45LDc0Ljk3NCw1MzIzLjcNCjE5OTksNDM5MS4yLDcxLjM4LDYxNjMuOA0KMjAwMCw0NjAyLjAsODIuMjk0LDcyODYuMw0KMjAwMSw0NzM5LjAsNzEuNTY2LDY1MjUuOQ0KMjAwMiw0NTgwLjYsNzAuNjQ3LDYyNzkuMw0KMjAwMyw0OTA0LjIsODAuNzM0LDc5OTguODMxMDM0NjMNCjIwMDQsNTQxMi41LDEzMC4xMDYsMTUzOTIuMTE1MjYzMzUNCjIwMDUsNTMyMC41LDE2Ny4wODcsMTk5MTEuNjg5NjY0MjYNCjIwMDYsNTM2MC44LDMwNS4yOTUsMzM5OTAuMTg3ODU1NTENCjIwMDcsNTU1Ny4wLDMyMy4yNDYsMzkxNDUuODkyNjc0NzYNCjIwMDgsNTMyNy42LDMxNS4zMTYsMzE2ODguMDU1MjQyNzgNCjIwMDksNTM5NC40LDIzNC4yMTcsMjk2MzcuMzE3NDEwOA0KMjAxMCw1NDE4LjksMzQxLjk3OCw0MTI4NS45MjkwNTI3MzgNCjIwMTEsNTI2Mi44LDM5OS42NTYsNDQ2MjQuNjUxMDU5NDENCjIwMTIsNTQzMy45LDM2MC41OTMsNDE5MDYuMDY0Njk4DQoyMDEzLDU3NzYuMCwzMzIuMTIsMzk4OTEuNDY2Mzc2MDQ3DQoyMDE0LDU3NjEuMSwzMTEuMjU1LDM3MjU2LjY4NjcwOTkNCjIwMTUsNTc3Mi4xLDI0OS4yMjYsMjk5MzUuNDY3ODE4NDk4NA0KMjAxNiw1NTUyLjYsMjIwLjU2MywyNzkyNi45NjkxNTkNCjIwMTcsNTUwMy41LDI3OS42ODQsMzQwMDAuOTIwNTg1MDU2DQoyMDE4LDU4MzEuNiwyOTUuODgsMzU2MDUuMTk2NzU4MjYzNQ0KMjAxOSw1Nzg3LjQsMjcyLjE0MywzMjU3Mi45Mjg3MjQ0NzIyDQoyMDIwLDU3MzMuMSwyODAuMzQ5LDM4NDY3LjI0MzE1MjQzMzYNCjIwMjEsNTYyNC45LDQyMi42MzQsNTI1MzUuODEwNTY1MjUyNg0KMjAyMiw1MzI4LjMsMzk5LjAyNiw0Mzc4MC4yNzIwMjM0DQoyMDIzLDUyNTAuNCwzODQuNTQ1LDQyNjAzLjc2MTMyMDINCjIwMjQsNTUwNS45LDQxNC44OTEsNDk3MDguMzY5MjIwMg0K", BinaryEncoding.Base64),[Delimiter=",",Columns=4,Encoding=65001,QuoteStyle=QuoteStyle.Csv]),
			 Headers = Table.PromoteHeaders(Source,[PromoteAllScalars=true]),
			 Typed = Table.TransformColumnTypes(Headers,{{"year",Int64.Type},{"production_kt",type number},{"price_us_cent_lb",type number},{"exports_usd_m",type number}})
			in Typed
