"""Build bilingual case pages and portfolio copy from computed evidence."""
from pathlib import Path
import json,re,html,zipfile
R=Path(__file__).resolve().parents[1]
M=json.loads((R/'case-studies/summary.json').read_text())
cases=[
{'id':'copper-observatory','title':['Chile’s copper: volume versus value','Cobre chileno: volumen frente a valor'],'domain':['Mining · Official public data','Minería · Datos públicos oficiales'],
'question':['What should management monitor when export value grows faster than production?','¿Qué debe vigilar la gerencia cuando el valor exportado crece más que la producción?'],
'method':['Reconcile 49 annual observations from three Cochilco workbooks. Normalize years, verify one-to-one joins, compare growth rates and index each series to 1976. SQL window functions reproduce the annual changes.','Conciliación de 49 observaciones anuales de tres archivos Cochilco. Normalización de años, uniones uno a uno, variaciones e índices base 1976. Funciones de ventana SQL reproducen las variaciones.'],
'result':['In 2024 production rose 4.9%, nominal export value 16.7% and nominal LME price 7.9%. Export growth is not a production-growth metric.','En 2024 la producción creció 4,9%, el valor nominal exportado 16,7% y el precio nominal LME 7,9%. El crecimiento exportador no mide el crecimiento productivo.'],
'decision':['Maintain separate physical-volume, price and export-value indicators. Investigate their divergence before revising operating capacity assumptions.','Mantener indicadores separados de volumen físico, precio y valor exportado. Investigar sus diferencias antes de revisar supuestos de capacidad operativa.'],
'limits':['Aggregate annual history through 2024; no mine-level costs, sale contracts or export tonnage. Prices and export values are nominal. Correlation between changes (0.923) is descriptive, not causal. A source typo in 1951 lies outside the 1976–2024 scope; it was not silently corrected.','Historia anual agregada hasta 2024; sin costos por faena, contratos ni tonelaje exportado. Precios y exportaciones nominales. Correlación entre variaciones (0,923) descriptiva, no causal. Un error de año en 1951 está fuera del período; no se corrigió silenciosamente.'],
'source':'https://www.cochilco.cl/web/50-anios-de-la-mineria-en-cifras/','sourceLabel':'COCHILCO · 50 años de la minería en cifras','metric':'49','metricLabel':['years reconciled','años conciliados'],'tech':'SQL · Python · Excel · Power BI','data':'annual.csv'},
{'id':'feria-demand','title':['A forecast a small business can operate','Un pronóstico que una feria puede operar'],'domain':['Demand planning · Synthetic simulation','Planificación de demanda · Simulación sintética'],
'question':['With only date, product and demand, can a transparent forecast improve on repeating last week?','Con solo fecha, producto y demanda, ¿un pronóstico transparente mejora repetir la última semana?'],
'method':['Generate 140,288 daily records for 128 products with a fixed seed. Compare seasonal naive with an eight-week weekday mean over four validation origins; reserve December for one final 28-day hold-out. Forecasts remain fixed at each origin.','Generar 140.288 registros diarios de 128 productos con semilla fija. Comparar naive estacional con promedio de ocho semanas por día, en cuatro orígenes de validación; reservar diciembre como prueba final de 28 días. Cada pronóstico queda fijo en su origen.'],
'result':['The weekday mean reduces held-out WMAPE from 44.6% to 35.9%: a 19.4% relative reduction. 69 products enter volume class A, including the item crossing the 80% threshold.','El promedio por día reduce WMAPE de prueba de 44,6% a 35,9%: una reducción relativa de 19,4%. 69 productos quedan en clase A por volumen, incluyendo el que cruza el umbral de 80%.'],
'decision':['Start with the weekday mean as a planning input. Collect stock availability, lead times and actual transactions before recommending reorder quantities or monetizing savings.','Usar el promedio por día como insumo de planificación. Recopilar disponibilidad, plazos y transacciones reales antes de recomendar cantidades de reposición o monetizar ahorros.'],
'limits':['All records are synthetic, not reconstructed client evidence. No prices, lost-sales observations, stock, shelf life or lead times. Volume classes are not revenue ABC. Results describe this generator, not a real business or service-level improvement.','Todos los registros son sintéticos, no evidencia reconstruida de un cliente. Sin precios, ventas perdidas, stock, vida útil ni plazos. La clasificación por volumen no es ABC de ingresos. Resultados de este generador, no de un negocio real ni de mejora de servicio.'],
'source':'https://github.com/Chrov/Portfolio/blob/main/tools/build_analysis.py','sourceLabel':'Reproducible generator · seed 20260907','metric':'19.4%','metricLabel':['less forecast error · simulated hold-out','menos error · prueba simulada'],'tech':'SQL · Python · Excel · Tableau','data':'demand.csv'},
{'id':'bank-campaign','title':['When a banking model should not ship','Cuándo no desplegar un modelo bancario'],'domain':['Banking · Historical academic dataset','Banca · Dataset académico histórico'],
'question':['Can contact capacity be prioritized using information available before a call—and does that ranking survive a later cohort?','¿Se puede priorizar capacidad de contacto con información previa a la llamada y mantener el desempeño en una cohorte posterior?'],
'method':['Use UCI’s 41,188 chronologically ordered records. Split 60/20/20 without shuffling, fit preprocessing on training only and exclude call duration, current campaign count and demographic fields. Audit ranking and calibration on reserved data.','Usar los 41.188 registros cronológicos de UCI. Separar 60/20/20 sin mezclar, ajustar transformaciones solo en entrenamiento y excluir duración, contactos de campaña actual y demografía. Auditar ranking y calibración en datos reservados.'],
'result':['Held-out AUC is 0.458. At 20% capacity the model captures 26.7% of observed subscribers, but the response rate shifts from 4.8% in training to 30.8% in hold-out. The positive top-capacity lift does not rescue overall ranking or calibration.','AUC de prueba de 0,458. Con 20% de capacidad captura 26,7% de suscriptores observados, pero la tasa cambia de 4,8% en entrenamiento a 30,8% en prueba. El lift positivo a capacidad limitada no rescata el ranking global ni la calibración.'],
'decision':['Do not deploy this model. Investigate cohort construction and macroeconomic drift, obtain recent pre-contact data and validate a new policy before an experiment. No campaign ROI or causal uplift is claimed.','No desplegar este modelo. Investigar composición de cohortes y cambio macroeconómico, obtener datos recientes previos al contacto y validar otra política antes de experimentar. No se afirma ROI ni uplift causal.'],
'limits':['Portuguese campaigns from 2008–2010, not current Chilean banking. UCI supplies row order but no exact dates or customer IDs; repeat-client leakage cannot be ruled out. Outcome is term-deposit subscription, not default risk. Reported capture is observational. Validation AP was already below cohort prevalence; hold-out is a diagnostic audit, not evidence supporting deployment.','Campañas portuguesas de 2008–2010, no banca chilena actual. UCI aporta orden pero no fechas exactas ni IDs; no se descarta repetición de clientes entre particiones. Se predice suscripción de depósitos, no impago. Captura observacional. AP de validación ya inferior a prevalencia; prueba final diagnóstica, no evidencia para desplegar.'],
'source':'https://archive.ics.uci.edu/dataset/222/bank+marketing','sourceLabel':'Moro, Rita & Cortez (2014) · UCI · CC BY 4.0 · DOI 10.24432/C5K306','metric':'0.458','metricLabel':['held-out AUC · model rejected','AUC de prueba · modelo rechazado'],'tech':'SQL · Python · Logistic regression · Excel','data':'holdout_scores.csv'}]
labels={'question':['Business question','Pregunta de negocio'],'method':['Method & validation','Método y validación'],'result':['What the data says','Qué dicen los datos'],'decision':['Recommendation','Recomendación'],'limits':['Limits of the evidence','Límites de la evidencia']}
dictionary={'en':{},'es':{}}
cards=[]
for case in cases:
 folder=R/'case-studies'/case['id'];slug=case['id']
 with zipfile.ZipFile(folder/'evidence-pack.zip','w',zipfile.ZIP_DEFLATED) as z:
  for name in ['dashboard.xlsx','analysis.sql','metrics.json','provenance.json',case['data']]:z.write(folder/name,name)
  if slug=='copper-observatory':
   for p in (folder/'powerbi').rglob('*'):
    if p.is_file() and '.pbi' not in p.parts:z.write(p,str(p.relative_to(folder)).replace('\\','/'))
  if slug=='feria-demand':z.write(folder/'dashboard.twbx','dashboard.twbx')
 for i,lang in enumerate(['en','es']):
  md=f"# {case['title'][i]}\n\n{case['domain'][i]}\n\n"
  for field in labels:md+=f"## {labels[field][i]}\n\n{case[field][i]}\n\n"
  md+=f"## {'Source and artifacts' if lang=='en' else 'Fuente y archivos'}\n\n[{case['sourceLabel']}]({case['source']})\n\n![Evidence](evidence.png)\n\n- [Excel dashboard and native PivotTable](dashboard.xlsx)\n- [SQL](analysis.sql)\n- [Data]({case['data']})\n- [Computed metrics](metrics.json)\n- [Source hashes](provenance.json)\n\n"
  md+='## Reproduce / Reproducir\n\nFrom the repository root / Desde la raíz:\n\n```sh\npython -m pip install -r tools/requirements-analysis.txt\npython tools/build_analysis.py\n```\n\nThe source workbooks and UCI archive are included; the generator has a fixed seed. Python asserts row coverage, keys, nonnegative demand and agreement with SQL. See tools/build_workbooks.mjs and tools/finalize_excel.ps1 for Excel; the latter requires Windows Excel.\n'
  if slug=='copper-observatory':
   md+='\n## Power BI\n\n[PBIP project](powerbi/Copper.pbip), two language pages, six bound visuals, DAX measures and a portable Power Query snapshot. The official report-authoring validator reports zero errors/warnings. Opened, refreshed and visually checked in Power BI Desktop on 2026-09-08. This is not a published Power BI Service report. Regenerate the snapshot with `python tools/build_powerbi.py` after updating the sources.\n'
  if slug=='feria-demand':
   md+='\n## Tableau\n\n[Packaged workbook](dashboard.twbx) contains three Hyper extracts, four worksheets and one bilingual dashboard. Extract contents and XML are validated. Opened and visually checked in Tableau Public Desktop on 2026-09-08. Tableau Public publication still requires sign-in. This is a generated workbook, not a claim of a live published dashboard.\n'
  (folder/('README.md' if lang=='en' else 'README.es.md')).write_text(md,encoding='utf-8')
  for key in ['title','domain','question','method','result','decision','limits','metricLabel']:
   dictionary[lang][slug+'.'+key]=case[key][i]
 sections=''.join(f'<section><h2><span lang="en">{labels[k][0]}</span><span lang="es">{labels[k][1]}</span></h2><p lang="en">{html.escape(case[k][0])}</p><p lang="es">{html.escape(case[k][1])}</p></section>' for k in labels)
 page=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{case['title'][0]} — Camilo Vergara</title><link rel="stylesheet" href="../../styles.css"><style>html[lang=en] [lang=es],html[lang=es] [lang=en]{{display:none}}main{{max-width:1000px;margin:auto;padding:40px 24px}}section{{margin:36px 0}}p{{max-width:75ch}}h1{{font-family:var(--font-display);font-size:clamp(2rem,4vw,3.5rem);line-height:1.15;margin:32px 0}}h2{{font-size:1.3rem;margin-bottom:12px}}img{{width:100%;height:auto;margin:28px 0}}.downloads{{display:flex;gap:18px;flex-wrap:wrap}}button{{font:inherit;padding:8px 14px;background:var(--surface);border:1px solid var(--border);cursor:pointer}}</style></head><body><main><nav class="downloads"><a href="../../index.html#projects">← Portfolio</a><button onclick="document.documentElement.lang='en'">English</button><button onclick="document.documentElement.lang='es'">Español</button></nav><h1><span lang="en">{case['title'][0]}</span><span lang="es">{case['title'][1]}</span></h1><p lang="en">{case['domain'][0]}</p><p lang="es">{case['domain'][1]}</p><img src="evidence.png" alt="Computed analytical charts; results and limitations described below" width="1950" height="720">{sections}<section><h2>Downloads / Descargas</h2><div class="downloads"><a href="dashboard.xlsx" download>Excel + PivotTable</a><a href="evidence-pack.zip" download>Evidence pack / Paquete</a><a href="https://github.com/Chrov/Portfolio/tree/main/case-studies/{slug}">GitHub</a><a href="{case['source']}">Source / Fuente</a></div></section></main></body></html>'''
 (folder/'index.html').write_text(page,encoding='utf-8')
 with zipfile.ZipFile(folder/'evidence-pack.zip','a',zipfile.ZIP_DEFLATED) as z:
  for name in ['README.md','README.es.md']:z.write(folder/name,name)
 cards.append(f'''<article class="evidence-case"><div class="evidence-case__copy"><p class="evidence-domain" data-i18n="{slug}.domain">{case['domain'][0]}</p><h3 data-i18n="{slug}.title">{case['title'][0]}</h3><p data-i18n="{slug}.question">{case['question'][0]}</p><p class="evidence-result" data-i18n="{slug}.result">{case['result'][0]}</p><p class="evidence-decision" data-i18n="{slug}.decision">{case['decision'][0]}</p><p class="evidence-stack">{case['tech']}</p><div class="evidence-links"><a class="btn btn--primary" href="case-studies/{slug}/index.html" data-i18n="evidence.read">Read case study</a><a href="case-studies/{slug}/dashboard.xlsx" download>Excel + PivotTable</a><a href="https://github.com/Chrov/Portfolio/tree/main/case-studies/{slug}">GitHub</a></div></div><a class="evidence-image" href="case-studies/{slug}/index.html"><img src="case-studies/{slug}/evidence.png" alt="{case['title'][0]}: analytical results" width="1950" height="720" loading="lazy"></a></article>''')
updates={
'hero.tagline':['From business questions to decisions you can audit.','De preguntas de negocio a decisiones que puedes revisar.'],
'hero.summary':['Data Analyst focused on SQL, Python, Excel and business intelligence. Explore public-data studies and clearly identified simulations: the method, the result and the limits behind each recommendation.','Data Analyst enfocado en SQL, Python, Excel e inteligencia de negocios. Explora análisis de datos públicos y simulaciones identificadas: método, resultado y límites detrás de cada recomendación.'],
'proj.title':['The evidence behind the decision','La evidencia detrás de la decisión'],
'proj.lead':['Three business questions. Reproducible data, transparent validation and downloadable workbooks.','Tres preguntas de negocio. Datos reproducibles, validación transparente y archivos descargables.'],
'evidence.read':['Read case study','Leer caso completo'],
'about.p2':['My professional background is in compliance reporting, SQL automation and BI. The public studies above are separate analytical demonstrations; they do not recreate confidential employment records.','Mi experiencia profesional se centra en reportes de cumplimiento, automatización SQL y BI. Los casos públicos son demostraciones analíticas independientes; no recrean registros laborales confidenciales.'],
'exp.job2.role':['Independent project — Market demand analytics','Proyecto independiente — Analítica de demanda de feria'],
'exp.job2.period':['Sep 2026','Sep 2026'],
'exp.job2.company':['Market demand simulation · Independent project','Simulación de demanda de feria · Proyecto independiente'],
'exp.job2.b1':['Developed a reproducible simulation inspired by a small market business.','Desarrollé una simulación reproducible inspirada en un negocio de feria.'],
'exp.job2.b2':['Structured product demand and compared transparent forecast baselines.','Estructuré demanda por producto y comparé pronósticos transparentes.'],
'exp.job2.b3':['Separated observed data, assumptions and simulated outcomes in project documentation.','Separé datos observados, supuestos y resultados simulados en la documentación.'],
'exp.job2.b4':['Prepared SQL analysis and downloadable workbooks for review.','Preparé análisis SQL y archivos descargables para revisión.']}
for key,pair in updates.items():
 for i,lang in enumerate(['en','es']):dictionary[lang][key]=pair[i]
(R/'case-content.js').write_text('window.PORTFOLIO_I18N = '+json.dumps(dictionary,ensure_ascii=False,indent=2)+';\n',encoding='utf-8')
page=(R/'index.html').read_text(encoding='utf-8')
start=page.index('    <section id="projects"');end=page.index('</section>',start)+len('</section>')
page=page[:start]+f'''    <section id="projects" class="section"><div class="container"><h2 class="section__title" data-i18n="proj.title">{updates['proj.title'][0]}</h2><p class="section__lead" data-i18n="proj.lead">{updates['proj.lead'][0]}</p>{''.join(cards)}</div></section>'''+page[end:]
page=re.sub(r'      <div class="hero__stats">.*?(?=      <div class="hero__social">)','',page,flags=re.S)
if 'src="case-content.js"' not in page:
 page=page.replace('  <script src="script.js"></script>','  <script src="case-content.js"></script>\n  <script src="script.js"></script>')
for key, pair in updates.items():
 page=re.sub(r'(<[^>]+data-i18n="'+re.escape(key)+r'"[^>]*>)[^<]*(</[^>]+>)',lambda m:m[1]+html.escape(pair[0])+m[2],page)
(R/'index.html').write_text(page,encoding='utf-8')
script=(R/'script.js').read_text(encoding='utf-8')
if 'Object.assign(I18N[lang]' not in script:
 script=script.replace('/* ===== Init ===== */','/* ===== Init ===== */\nfor (const lang of ["en", "es"]) Object.assign(I18N[lang], window.PORTFOLIO_I18N?.[lang] || {});')
if 'if (document.getElementById("repoGrid")) loadRepos();' not in script:
 script=script.replace('loadRepos();','if (document.getElementById("repoGrid")) loadRepos();')
(R/'script.js').write_text(script,encoding='utf-8')
print('Wrote 3 bilingual studies and portfolio integration')
